"""Initial schema

Revision ID: 0d14a49ea999
Revises: 
Create Date: 2026-06-26 15:27:24.824112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d14a49ea999'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('provider', sa.String(length=500), nullable=False),
    sa.Column('amount_min', sa.Float(), nullable=True),
    sa.Column('amount_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('renewable', sa.Boolean(), nullable=True),
    sa.Column('degree_levels', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('fields_of_study', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('eligible_nationalities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('eligible_countries', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('gpa_requirement', sa.Float(), nullable=True),
    sa.Column('income_requirement', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility_text', sa.Text(), nullable=True),
    sa.Column('requirements', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scholarship_created', 'scholarships', ['created_at'], unique=False)
    op.create_index('idx_scholarship_deadline_active', 'scholarships', ['is_active', 'deadline'], unique=False)
    op.create_table('scrape_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spider_name', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('records_scraped', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('degree_level', sa.String(length=100), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('country_of_residence', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('disability', sa.String(length=255), nullable=True),
    sa.Column('income_bracket', sa.String(length=100), nullable=True),
    sa.Column('extracurriculars', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('target_destinations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('max_sources', sa.Integer(), server_default='5', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('saved_scholarships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scholarship_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_scholarships')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scrape_logs')
    op.drop_index('idx_scholarship_deadline_active', table_name='scholarships')
    op.drop_index('idx_scholarship_created', table_name='scholarships')
    op.drop_table('scholarships')
    # ### end Alembic commands ###
